/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.binus.takenote.model;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;
import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.EntireEncrypted;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.Indexes;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;

import java.util.Date;

/**
 * Definition of ObjectType NoteDB.
 *
 * @since 2022-01-15
 */
@PrimaryKeys({"id"})
@Indexes({"NoteIndex:id"})
public final class NoteDB extends CloudDBZoneObject {
    private String id;

    @NotNull
    @DefaultValue(stringValue = "-")
    private String userId;

    @NotNull
    @DefaultValue(stringValue = "-")
    private String title;

    @NotNull
    @DefaultValue(stringValue = "-")
    private String content;

    private Date date;

    public NoteDB() {
        super(NoteDB.class);
        this.userId = "-";
        this.title = "-";
        this.content = "-";
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getUserId() {
        return userId;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getTitle() {
        return title;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getContent() {
        return content;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public Date getDate() {
        return date;
    }

}
